# SPDX-License-Identifier: MIT
# Copyright (c) 2026 TrendVidia, LLC.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(actions)"
    open-pull-requests-limit: 5
    groups:
      actions-minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(swift)"
    open-pull-requests-limit: 5
    groups:
      swift-minor-and-patch:
        update-types: ["minor", "patch"]
