// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: envelope/v1/envelope.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Standard response envelope for API integration.
//
// Provides a uniform structure for API responses regardless of wire format
// (JSON, protobuf, PXF). The envelope separates transport-level errors from
// application-level errors, and carries machine-readable error codes with
// positional format arguments for client-side localization.
//
// Error localization convention:
//   - AppError.code maps to string table key "error.<CODE>"
//   - FieldError.code maps to string table key "field.<CODE>"
//   - args provide positional values for {0}, {1}, ... placeholders
//   - message field is a server-side fallback if the client has no string table entry

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Envelope wraps every API response with transport metadata,
/// application-level error handling, and the success payload.
///
/// Usage pattern:
///   - Success: status=200, data populated, error empty
///   - App error: status=200 (or 4xx), error populated, data empty
///   - Transport error: transport_error set, everything else empty
public struct Envelope_V1_Envelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Transport layer.
  public var status: Int32 = 0

  /// network-level error (timeout, connection refused)
  public var transportError: String = String()

  /// Application layer — the response payload on success.
  /// Encoded as nested PXF block or JSON object. The border codec
  /// flattens this into state store keys.
  public var data: Data = Data()

  /// Application layer — set when business logic fails.
  public var error: Envelope_V1_AppError {
    get {_error ?? Envelope_V1_AppError()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Envelope_V1_AppError? = nil
}

/// AppError represents an application-level error with a machine-readable code,
/// positional format arguments for localized display, and optional field-level details.
///
/// Localization: clients look up "error.<code>" in their string table and
/// substitute args as {0}, {1}, etc. The message field is a fallback.
public struct Envelope_V1_AppError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Machine-readable error code: "INSUFFICIENT_FUNDS", "AUTH_REQUIRED", "NOT_FOUND".
  /// Maps to string table key "error.<code>".
  public var code: String = String()

  /// Server-side human-readable message. Used as fallback when the client's
  /// string table has no entry for this code.
  public var message: String = String()

  /// Positional format arguments for the localized message template.
  /// Example: code="INSUFFICIENT_FUNDS", args=["$3.50", "$10.00"]
  ///   → string table: "error.INSUFFICIENT_FUNDS" = "Your balance is {0}, minimum is {1}"
  ///   → display: "Your balance is $3.50, minimum is $10.00"
  public var args: [String] = []

  /// Per-field validation errors.
  public var details: [Envelope_V1_FieldError] = []

  /// Arbitrary metadata for client-side logic (retry_after, request_id, etc.).
  public var metadata: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// FieldError represents a validation error on a specific field.
/// Maps to UI form validation: the border codec can wire field errors
/// directly to Entry widget validators.
///
/// Localization: clients look up "field.<code>" in their string table
/// and substitute args as {0}, {1}, etc.
public struct Envelope_V1_FieldError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Field path matching the proto field name or PXF key: "amount", "user.email".
  public var field: String = String()

  /// Machine-readable error code: "REQUIRED", "MIN_VALUE", "INVALID_FORMAT", "UNIQUE".
  /// Maps to string table key "field.<code>".
  public var code: String = String()

  /// Server-side fallback message.
  public var message: String = String()

  /// Positional format arguments.
  /// Example: code="MIN_VALUE", args=["10.00"]
  ///   → string table: "field.MIN_VALUE" = "Minimum value is {0}"
  ///   → display: "Minimum value is 10.00"
  public var args: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "envelope.v1"

extension Envelope_V1_Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Envelope"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{3}transport_error\0\u{1}data\0\u{1}error\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.status) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.transportError) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.status != 0 {
      try visitor.visitSingularInt32Field(value: self.status, fieldNumber: 1)
    }
    if !self.transportError.isEmpty {
      try visitor.visitSingularStringField(value: self.transportError, fieldNumber: 2)
    }
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 3)
    }
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Envelope_V1_Envelope, rhs: Envelope_V1_Envelope) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.transportError != rhs.transportError {return false}
    if lhs.data != rhs.data {return false}
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Envelope_V1_AppError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AppError"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}message\0\u{1}args\0\u{1}details\0\u{1}metadata\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.args) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.details) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.args.isEmpty {
      try visitor.visitRepeatedStringField(value: self.args, fieldNumber: 3)
    }
    if !self.details.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.details, fieldNumber: 4)
    }
    if !self.metadata.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.metadata, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Envelope_V1_AppError, rhs: Envelope_V1_AppError) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.args != rhs.args {return false}
    if lhs.details != rhs.details {return false}
    if lhs.metadata != rhs.metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Envelope_V1_FieldError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FieldError"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}field\0\u{1}code\0\u{1}message\0\u{1}args\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.field) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.args) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.field.isEmpty {
      try visitor.visitSingularStringField(value: self.field, fieldNumber: 1)
    }
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 2)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 3)
    }
    if !self.args.isEmpty {
      try visitor.visitRepeatedStringField(value: self.args, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Envelope_V1_FieldError, rhs: Envelope_V1_FieldError) -> Bool {
    if lhs.field != rhs.field {return false}
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.args != rhs.args {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
