// SPDX-License-Identifier: MIT
// Copyright (c) 2026 TrendVidia, LLC.
// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pxf/annotations.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Extension support defined in annotations.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_FieldOptions {

  /// Mark a field as required in PXF. Absent fields cause a validation error.
  /// A field set to null still counts as present.
  public var Pxf_required: Bool {
    get {return getExtensionValue(ext: Pxf_Extensions_required) ?? false}
    set {setExtensionValue(ext: Pxf_Extensions_required, value: newValue)}
  }
  /// Returns true if extension `Pxf_Extensions_required`
  /// has been explicitly set.
  public var hasPxf_required: Bool {
    return hasExtensionValue(ext: Pxf_Extensions_required)
  }
  /// Clears the value of extension `Pxf_Extensions_required`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearPxf_required() {
    clearExtensionValue(ext: Pxf_Extensions_required)
  }

  /// Default value applied when a field is absent (not null) in PXF.
  /// The value is a PXF literal string, e.g. "42", "true", "\"hello\"".
  public var Pxf_default: String {
    get {return getExtensionValue(ext: Pxf_Extensions_default) ?? String()}
    set {setExtensionValue(ext: Pxf_Extensions_default, value: newValue)}
  }
  /// Returns true if extension `Pxf_Extensions_default`
  /// has been explicitly set.
  public var hasPxf_default: Bool {
    return hasExtensionValue(ext: Pxf_Extensions_default)
  }
  /// Clears the value of extension `Pxf_Extensions_default`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearPxf_default() {
    clearExtensionValue(ext: Pxf_Extensions_default)
  }

}

// MARK: - File's ExtensionMap: Pxf_Annotations_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
public let Pxf_Annotations_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Pxf_Extensions_required,
  Pxf_Extensions_default
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

/// Mark a field as required in PXF. Absent fields cause a validation error.
/// A field set to null still counts as present.
public let Pxf_Extensions_required = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufBool>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 50000,
  fieldName: "pxf.required"
)

/// Default value applied when a field is absent (not null) in PXF.
/// The value is a PXF literal string, e.g. "42", "true", "\"hello\"".
public let Pxf_Extensions_default = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 50001,
  fieldName: "pxf.default"
)
