// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pxf/bignum.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Arbitrary-precision signed integer.
/// Wire: unsigned big-endian absolute value + sign flag.
/// PXF text: bare integer literal.
public struct Pxf_BigInt {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var abs: Data = Data()

  public var negative: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Arbitrary-precision exact decimal: value = (-1)^negative × unscaled × 10^(-scale).
/// Wire: unsigned big-endian unscaled value + scale + sign flag.
/// PXF text: decimal literal preserving exact scale (e.g. "1.00" has scale=2).
public struct Pxf_Decimal {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unscaled: Data = Data()

  public var scale: Int32 = 0

  public var negative: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Arbitrary-precision binary floating point.
/// Wire: unsigned big-endian integer mantissa + binary exponent + precision + sign flag.
/// PXF text: float literal with arbitrary mantissa precision.
public struct Pxf_BigFloat {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mantissa: Data = Data()

  public var exponent: Int32 = 0

  public var prec: UInt32 = 0

  public var negative: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Pxf_BigInt: @unchecked Sendable {}
extension Pxf_Decimal: @unchecked Sendable {}
extension Pxf_BigFloat: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "pxf"

extension Pxf_BigInt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BigInt"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "abs"),
    2: .same(proto: "negative"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.abs) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.negative) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.abs.isEmpty {
      try visitor.visitSingularBytesField(value: self.abs, fieldNumber: 1)
    }
    if self.negative != false {
      try visitor.visitSingularBoolField(value: self.negative, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Pxf_BigInt, rhs: Pxf_BigInt) -> Bool {
    if lhs.abs != rhs.abs {return false}
    if lhs.negative != rhs.negative {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Pxf_Decimal: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Decimal"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "unscaled"),
    2: .same(proto: "scale"),
    3: .same(proto: "negative"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.unscaled) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.scale) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.negative) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.unscaled.isEmpty {
      try visitor.visitSingularBytesField(value: self.unscaled, fieldNumber: 1)
    }
    if self.scale != 0 {
      try visitor.visitSingularInt32Field(value: self.scale, fieldNumber: 2)
    }
    if self.negative != false {
      try visitor.visitSingularBoolField(value: self.negative, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Pxf_Decimal, rhs: Pxf_Decimal) -> Bool {
    if lhs.unscaled != rhs.unscaled {return false}
    if lhs.scale != rhs.scale {return false}
    if lhs.negative != rhs.negative {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Pxf_BigFloat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BigFloat"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "mantissa"),
    2: .same(proto: "exponent"),
    3: .same(proto: "prec"),
    4: .same(proto: "negative"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.mantissa) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.exponent) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.prec) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.negative) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mantissa.isEmpty {
      try visitor.visitSingularBytesField(value: self.mantissa, fieldNumber: 1)
    }
    if self.exponent != 0 {
      try visitor.visitSingularInt32Field(value: self.exponent, fieldNumber: 2)
    }
    if self.prec != 0 {
      try visitor.visitSingularUInt32Field(value: self.prec, fieldNumber: 3)
    }
    if self.negative != false {
      try visitor.visitSingularBoolField(value: self.negative, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Pxf_BigFloat, rhs: Pxf_BigFloat) -> Bool {
    if lhs.mantissa != rhs.mantissa {return false}
    if lhs.exponent != rhs.exponent {return false}
    if lhs.prec != rhs.prec {return false}
    if lhs.negative != rhs.negative {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
