// SPDX-License-Identifier: MIT
// Copyright (c) 2026 TrendVidia, LLC.
// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: sbe/annotations.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Extension support defined in annotations.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_FieldOptions {

  /// Fixed byte length for string and bytes fields.
  /// Values longer than this are truncated; shorter values are null-padded.
  public var Sbe_length: UInt32 {
    get {return getExtensionValue(ext: Sbe_Extensions_length) ?? 0}
    set {setExtensionValue(ext: Sbe_Extensions_length, value: newValue)}
  }
  /// Returns true if extension `Sbe_Extensions_length`
  /// has been explicitly set.
  public var hasSbe_length: Bool {
    return hasExtensionValue(ext: Sbe_Extensions_length)
  }
  /// Clears the value of extension `Sbe_Extensions_length`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearSbe_length() {
    clearExtensionValue(ext: Sbe_Extensions_length)
  }

  /// SBE primitive type override. Allows narrowing a proto type to a smaller
  /// SBE encoding, e.g. uint32 -> "uint8". Valid values:
  /// int8, int16, int32, int64, uint8, uint16, uint32, uint64, float, double.
  public var Sbe_encoding: String {
    get {return getExtensionValue(ext: Sbe_Extensions_encoding) ?? String()}
    set {setExtensionValue(ext: Sbe_Extensions_encoding, value: newValue)}
  }
  /// Returns true if extension `Sbe_Extensions_encoding`
  /// has been explicitly set.
  public var hasSbe_encoding: Bool {
    return hasExtensionValue(ext: Sbe_Extensions_encoding)
  }
  /// Clears the value of extension `Sbe_Extensions_encoding`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearSbe_encoding() {
    clearExtensionValue(ext: Sbe_Extensions_encoding)
  }
}

extension SwiftProtobuf.Google_Protobuf_FileOptions {

  /// SBE schema identifier. Required on files containing SBE messages.
  public var Sbe_schemaID: UInt32 {
    get {return getExtensionValue(ext: Sbe_Extensions_schema_id) ?? 0}
    set {setExtensionValue(ext: Sbe_Extensions_schema_id, value: newValue)}
  }
  /// Returns true if extension `Sbe_Extensions_schema_id`
  /// has been explicitly set.
  public var hasSbe_schemaID: Bool {
    return hasExtensionValue(ext: Sbe_Extensions_schema_id)
  }
  /// Clears the value of extension `Sbe_Extensions_schema_id`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearSbe_schemaID() {
    clearExtensionValue(ext: Sbe_Extensions_schema_id)
  }

  /// SBE schema version.
  public var Sbe_version: UInt32 {
    get {return getExtensionValue(ext: Sbe_Extensions_version) ?? 0}
    set {setExtensionValue(ext: Sbe_Extensions_version, value: newValue)}
  }
  /// Returns true if extension `Sbe_Extensions_version`
  /// has been explicitly set.
  public var hasSbe_version: Bool {
    return hasExtensionValue(ext: Sbe_Extensions_version)
  }
  /// Clears the value of extension `Sbe_Extensions_version`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearSbe_version() {
    clearExtensionValue(ext: Sbe_Extensions_version)
  }
}

extension SwiftProtobuf.Google_Protobuf_MessageOptions {

  /// SBE message template identifier. Required on each top-level SBE message.
  public var Sbe_templateID: UInt32 {
    get {return getExtensionValue(ext: Sbe_Extensions_template_id) ?? 0}
    set {setExtensionValue(ext: Sbe_Extensions_template_id, value: newValue)}
  }
  /// Returns true if extension `Sbe_Extensions_template_id`
  /// has been explicitly set.
  public var hasSbe_templateID: Bool {
    return hasExtensionValue(ext: Sbe_Extensions_template_id)
  }
  /// Clears the value of extension `Sbe_Extensions_template_id`.
  /// Subsequent reads from it will return its default value.
  public mutating func clearSbe_templateID() {
    clearExtensionValue(ext: Sbe_Extensions_template_id)
  }

}

// MARK: - File's ExtensionMap: Sbe_Annotations_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
public let Sbe_Annotations_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Sbe_Extensions_schema_id,
  Sbe_Extensions_version,
  Sbe_Extensions_template_id,
  Sbe_Extensions_length,
  Sbe_Extensions_encoding
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

/// SBE schema identifier. Required on files containing SBE messages.
public let Sbe_Extensions_schema_id = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufUInt32>, SwiftProtobuf.Google_Protobuf_FileOptions>(
  _protobuf_fieldNumber: 50100,
  fieldName: "sbe.schema_id"
)

/// SBE schema version.
public let Sbe_Extensions_version = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufUInt32>, SwiftProtobuf.Google_Protobuf_FileOptions>(
  _protobuf_fieldNumber: 50101,
  fieldName: "sbe.version"
)

/// SBE message template identifier. Required on each top-level SBE message.
public let Sbe_Extensions_template_id = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufUInt32>, SwiftProtobuf.Google_Protobuf_MessageOptions>(
  _protobuf_fieldNumber: 50200,
  fieldName: "sbe.template_id"
)

/// Fixed byte length for string and bytes fields.
/// Values longer than this are truncated; shorter values are null-padded.
public let Sbe_Extensions_length = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufUInt32>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 50300,
  fieldName: "sbe.length"
)

/// SBE primitive type override. Allows narrowing a proto type to a smaller
/// SBE encoding, e.g. uint32 -> "uint8". Valid values:
/// int8, int16, int32, int64, uint8, uint16, uint32, uint64, float, double.
public let Sbe_Extensions_encoding = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 50301,
  fieldName: "sbe.encoding"
)
